name: Setup
description: Setup the project

inputs:
  emsdk-version:
    description: EMSDK Version
    required: true
    default: 3.1.69
  emsdk-cache-dir:
    description: EMSDK Cache Directory
    required: true
    default: .emsdk-cache

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    - name: Setup EMSDK
      uses: ./.github/actions/setup-emsdk
      with:
        emsdk-version: ${{ inputs.emsdk-version }}
        emsdk-cache-dir: ${{ inputs.emsdk-cache-dir }}
