import { type ReaderOptions, defaultReaderOptions as ro } from "./index.js";

export const defaultReaderOptions: Required<ReaderOptions> = {
  ...ro,
  formats: [...ro.formats],
};

export {
  BARCODE_FORMATS,
  BARCODE_HRI_LABELS,
  BARCODE_META_FORMATS,
  BARCODE_SYMBOLOGIES,
  type BarcodeFormat,
  type BarcodeHriLabel,
  type BarcodeMetaFormat,
  type BarcodeSymbol,
  type BarcodeSymbology,
  BINARIZERS,
  type Binarizer,
  barcodeFormats,
  binarizers,
  CHARACTER_SETS,
  type CharacterSet,
  CONTENT_TYPES,
  type ContentType,
  CREATABLE_BARCODE_FORMATS,
  type CreatableBarcodeFormat,
  characterSets,
  contentTypes,
  EAN_ADD_ON_SYMBOLS,
  type EanAddOnSymbol,
  type EcLevel,
  eanAddOnSymbols,
  encodeFormat,
  encodeFormats,
  formatToLabel,
  formatToSymbology,
  GS1_BARCODE_FORMATS,
  type GS1BarcodeFormat,
  INDUSTRIAL_BARCODE_FORMATS,
  type IndustrialBarcodeFormat,
  LINEAR_BARCODE_FORMATS,
  type LinearBarcodeFormat,
  type LooseBarcodeFormat,
  linearBarcodeFormats,
  MATRIX_BARCODE_FORMATS,
  type MatrixBarcodeFormat,
  matrixBarcodeFormats,
  type Point,
  type Position,
  READABLE_BARCODE_FORMATS,
  RETAIL_BARCODE_FORMATS,
  type ReadableBarcodeFormat,
  type ReaderOptions,
  type ReadInputBarcodeFormat,
  type ReadOutputBarcodeFormat,
  type ReadResult,
  type RetailBarcodeFormat,
  symbologyToFormats,
  TEXT_MODES,
  type TextMode,
  textModes,
  type ZXingPoint,
  type ZXingPosition,
  type ZXingReaderOptions,
  type ZXingReadResult,
  type ZXingVector,
} from "./index.js";
