import { type WriterOptions, defaultWriterOptions as wo } from "./index.js";

export const defaultWriterOptions: Required<WriterOptions> = { ...wo };

export {
  BARCODE_FORMATS,
  BARCODE_HRI_LABELS,
  BARCODE_META_FORMATS,
  BARCODE_SYMBOLOGIES,
  type BarcodeFormat,
  type BarcodeHriLabel,
  type BarcodeMetaFormat,
  type BarcodeSymbol,
  type BarcodeSymbology,
  barcodeFormats,
  CHARACTER_SETS,
  type CharacterSet,
  CREATABLE_BARCODE_FORMATS,
  type CreatableBarcodeFormat,
  characterSets,
  type EcLevel,
  encodeFormat,
  encodeFormats,
  formatToLabel,
  formatToSymbology,
  GS1_BARCODE_FORMATS,
  type GS1BarcodeFormat,
  INDUSTRIAL_BARCODE_FORMATS,
  type IndustrialBarcodeFormat,
  LINEAR_BARCODE_FORMATS,
  type LinearBarcodeFormat,
  type LooseBarcodeFormat,
  linearBarcodeFormats,
  MATRIX_BARCODE_FORMATS,
  type MatrixBarcodeFormat,
  matrixBarcodeFormats,
  READABLE_BARCODE_FORMATS,
  RETAIL_BARCODE_FORMATS,
  type ReadableBarcodeFormat,
  type RetailBarcodeFormat,
  symbologyToFormats,
  type WriteInputBarcodeFormat,
  type WriteResult,
  type WriterOptions,
  type ZXingWriteResult,
  type ZXingWriterOptions,
} from "./index.js";
