name: Setup EMSDK
description: Setup the EMSDK environment

inputs:
  emsdk-version:
    description: EMSDK Version
    required: true
  emsdk-cache-dir:
    description: EMSDK Cache Directory
    required: true

runs:
  using: composite
  steps:
    - name: Setup System Libraries Cache
      id: cache-system-libraries
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
      with:
        path: ${{ inputs.emsdk-cache-dir }}
        key: ${{ inputs.emsdk-version }}-${{ runner.os }}

    - name: Setup EMSDK
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk-version }}
        actions-cache-folder: ${{ inputs.emsdk-cache-dir }}

    - name: Patch emscripten
      shell: bash
      # You need to checkout the zxing-wasm repo first!
      run: |
        git apply ./emscripten.patch --unsafe-paths --directory="$(dirname $(which emcc))" --check --stat -v
        git apply ./emscripten.patch --unsafe-paths --directory="$(dirname $(which emcc))"
