name: Setup EMSDK
description: Setup the EMSDK environment

inputs:
  emsdk-version:
    description: EMSDK Version
    required: true
  emsdk-cache-dir:
    description: EMSDK Cache Directory
    required: true

runs:
  using: composite
  steps:
    - name: Setup System Libraries Cache
      id: cache-system-libraries
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ${{ inputs.emsdk-cache-dir }}
        key: ${{ inputs.emsdk-version }}-${{ runner.os }}

    - name: Setup EMSDK
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk-version }}
        actions-cache-folder: ${{ inputs.emsdk-cache-dir }}

    - name: Patch emscripten
      shell: bash
      # You need to checkout the zxing-wasm repo first!
      run: |
        PATCH_FILE="./emscripten.patch"
        EMSCRIPTEN_DIR="$(dirname $(which emcc))"

        # First, check if the patch is already applied
        if git apply --reverse --check --unsafe-paths --directory="$EMSCRIPTEN_DIR" "$PATCH_FILE"; then
          echo "Patch already applied, skipping..."
        else
          # Try to apply the patch
          if git apply --unsafe-paths --directory="$EMSCRIPTEN_DIR" "$PATCH_FILE"; then
            echo "Patch applied successfully."
          else
            echo "Failed to apply patch." >&2
            exit 1
          fi
        fi
