name: Delete PR Prereleases

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  contents: write

jobs:
  delete-pr-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number
        id: get-pr-number
        uses: mgaitan/gha-get-pr-number@main

      - name: Delete PR Prereleases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: pr-${{ steps.get-pr-number.outputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
