name: Preview Release

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Bump Version
        run: pnpm -s changeset version

      - name: Build
        run: pnpm -s prepublishOnly

      - name: Publish Preview Release
        run: pnpx pkg-pr-new publish --compact
