name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  EM_VERSION: 3.1.52
  EM_CACHE_FOLDER: ".emsdk-cache"
  NPM_CONFIG_PROVENANCE: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup System Libraries Cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{ env.EM_CACHE_FOLDER }}
          key: ${{ env.EM_VERSION }}-${{ runner.os }}

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Install Dependencies
        run: npm ci

      - name: Get Next Package Version
        id: package-version
        run: echo "version=$(npx changeset status --output=release.json && jq -r '.releases[0].newVersion // '$(npm pkg get version)'' release.json && rm release.json)" >> $GITHUB_OUTPUT

      - name: Get Commit ID
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get-commit-id
        run: |
          echo "short-commit-id=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
          echo "commit-id=$(git rev-parse $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - name: Manual Bump, Build and Pack
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npm run bump
          npm run build:all
          npm pack

      - name: Delete Previous Draft Releases
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: false
          pre-release-drop: false
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Manual Draft Release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "zxing-wasm-${{ steps.package-version.outputs.version }}.tgz"
          artifactContentType: application/gzip
          body: "This is a draft release of zxing-wasm: ${{ steps.get-commit-id.outputs.short-commit-id }}."
          commit: ${{ steps.get-commit-id.outputs.commit-id }}
          tag: "v${{ steps.package-version.outputs.version }}-draft.${{ steps.get-commit-id.outputs.short-commit-id }}"
          draft: true
          name: "zxing-wasm v${{ steps.package-version.outputs.version }}-draft.${{ steps.get-commit-id.outputs.short-commit-id }}"
          removeArtifacts: true

      - name: Create Release Pull Request or Publish to NPM
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run bump
          publish: npx changeset publish
          commit: "chore(release): v${{ steps.package-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
