name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write

env:
  NPM_CONFIG_PROVENANCE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        uses: ./.github/actions/test

      - name: Get Next Package Version
        id: package-version
        run: echo "version=$(pnpm -s changeset status --output=release.json && jq -r '.releases[0].newVersion // '$(npm pkg get version)'' release.json && rm release.json)" >> $GITHUB_OUTPUT

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@3de3850952bec538fde60aac71731376e57b9b57 # v1.4.8
        with:
          publish: pnpm -s changeset publish
          commit: "chore(release): v${{ steps.package-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
