name: Size

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    name: BundleWatch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build artifacts
        run: pnpm -s build:all

      - name: BundleWatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_BRANCH_BASE: ${{ github.base_ref || github.event.repository.default_branch }}
        run: pnpm -s bundlewatch
